// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5pLUtdDV3B3NkmzZ-DbQJY-YIQOlc3xA',
    appId: '1:562553165879:web:40f7258a3985dafdcdc7b2',
    messagingSenderId: '562553165879',
    projectId: 'ezerfresh-f87af',
    authDomain: 'ezerfresh-f87af.firebaseapp.com',
    storageBucket: 'ezerfresh-f87af.firebasestorage.app',
    measurementId: 'G-T69TWKT6KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD2DchR_hXFflK9lf4OkW5Y0gmr7XUW98',
    appId: '1:562553165879:android:0ea5189fe28e5024cdc7b2',
    messagingSenderId: '562553165879',
    projectId: 'ezerfresh-f87af',
    storageBucket: 'ezerfresh-f87af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-dTMYIo-SvZqxG_xQw3uSdji9cZ6ijI',
    appId: '1:562553165879:ios:1b5db6ca9d1e9695cdc7b2',
    messagingSenderId: '562553165879',
    projectId: 'ezerfresh-f87af',
    storageBucket: 'ezerfresh-f87af.firebasestorage.app',
    iosBundleId: 'com.ezerfresh.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5pLUtdDV3B3NkmzZ-DbQJY-YIQOlc3xA',
    appId: '1:562553165879:web:1fb167bab24a2552cdc7b2',
    messagingSenderId: '562553165879',
    projectId: 'ezerfresh-f87af',
    authDomain: 'ezerfresh-f87af.firebaseapp.com',
    storageBucket: 'ezerfresh-f87af.firebasestorage.app',
    measurementId: 'G-0YWSR1ZBQV',
  );
}
